config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :path => '',
    :path_names => {:sign_in => 'login', :sign_out => 'logout'},
    :controllers => { registrations: 'registrations' }

  resources :clients do
    resources :action_plans, shallow: true, except: [:index]
  end

  resources :action_plans, shallow: true, only: [] do
    resources :goals, shallow: true, except: [:index]
  end

  resources :goals, shallow: true, only: [] do
    resources :steps, shallow: true, except: [:index, :destroy]
  end

  resources :steps, shallow: true, only: [] do
    resources :text_messages, shallow: true, except: [:index]
  end

  get "text_messages/receive"
  match '/receivetext' => 'text_messages#receive', :via => :post

  resources :clients do
    collection do
      post :welcome
    end
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'group_new' => 'text_messages#group_new'
  post 'group_create' => 'text_messages#group_create'

  root to: 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user

  has_many :action_plans, dependent: :destroy
  has_many :text_messages

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true, format: { with: /\A\+1\d{10}\z/,
    message: "number format is +1 followed by the rest of the phone number. Example: +14152823334"}
  # Remove validation to allow YMCA signups
  #validates :salesforce_id, length: { minimum: 15, 
    #message: "ID is too short, if you do not wish to enter a Salesforce ID then simply enter a random sequence e.g. '123456789123456'" }
  #validates :contact_id, length: { minimum: 7 }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # Implemented for CORS - 'Cross-Origin Resource Sharing' for JSON and RAILS #
  before_filter :authenticate_user!
  before_filter :set_headers

  def index
    @clients = current_user.clients.order(:last_name)
    respond_with @clients
  end

  def new
    @client = current_user.clients.new
  end

  def create
    @client = current_user.clients.build(client_params)

    authorize @client
    if @client.save
      flash[:notice] = "Success! Client was saved."
      redirect_to @client
    else
      puts @client.params
      flash[:error] = @client.errors.full_messages
      render :new
    end
  end

  def show
    @client = current_user.clients.find(params[:id])
    @action_plans = @client.action_plans.all
    @outgoing_texts = TextMessage.where(client_id: @client.id).where(incoming_message: "false")
    @incoming_texts = TextMessage.where(client_id: @client.id).where(incoming_message: "true")
  end

  def edit
    @client = current_user.clients.find(params[:id])
  end

  def update
    @client = current_user.clients.find(params[:id])
    if @client.update_attributes(client_params)
      flash[:notice] = "Success! Client was updated."
      redirect_to @client
    else
      flash[:error] = "There was an error saving the client. Please try again."
      render :edit
    end
  end

  def destroy
    @client = current_user.clients.find(params[:id])
    first_name = @client.first_name
    if @client.destroy
      flash[:notice] = "\"#{first_name}\" was deleted successfully."
      redirect_to clients_path
    else
      flash[:error] = "There was an error deleting the client."
      render :show
    end
  end

  def welcome
    @client = current_user.clients.find(params[:client])
    @text_message=TextMessage.create!(scheduled_date: Date.today, client_id: @client.id, content: "Welcome to #{ENV['NON_PROFIT']}, #{@client.first_name}. Please save this number as #{@client.user.first_name}. I'll be texting you with reminders. Text back if you need help!", phone: @client.phone, incoming_message: "false", sentstatus: "false")
    @text_message.scheduled_time = Time.now.in_time_zone("Pacific Time (US & Canada)")
    @text_message.send_text_message(@text_message.content, @text_message.phone)

    if (@text_message.save && (@text_message.sentstatus == true))
      flash[:notice] = "Text was sent: \"#{@text_message.content}\""
      redirect_to clients_path
    else
      flash[:error] = "There was an error sending your welcome text. Please try again."
    end
  end

  private

    def client_params
      params.require(:client).permit(:first_name, :last_name, :phone, :salesforce_id, :contact_id, :email)
    end

    def set_headers
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Expose-Headers'] = 'ETag'
      headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
      headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match'
      headers['Access-Control-Request-Method'] = '*'
      headers['Access-Control-Max-Age'] = '86400'
    end
end

app/views/clients/_client.html.erb
<%= div_for client do %>
	<%= link_to "#{client.last_name}, #{client.first_name}", client %>
	<%= client.email %>
	<%= client.phone %>
  <%= client.contact_id %>
	<%= client.salesforce_id %>
<% end %>

app/views/clients/_client_sidebar.html.erb
<div class="sidebar">
	<%= div_for @client do%>
		<h2>
			<%= link_to "#{@client.first_name} #{@client.last_name}", client_path(@client.id) %>
		</h2>

		<h4 class="narrow">
			MEDA Client
		</h4>
		<h4 class="narrow">
			<%= @client.email %>
		</h4>
		<h4 class="narrow">
			<%= @client.phone %>
		</h4>
		<h4 class="narrow">
			Contact ID:<%= @client.contact_id %>
		</h4>
		<h4 class="narrow">
			Salesforce ID:<%= @client.salesforce_id %>
		</h4>
		<h4 class="narrow">
			<%= link_to "edit", edit_client_path(@client) %>
		</h4>	
	<% end %>
</div>

app/views/clients/_form.html.erb
<div>
	<%= form_for @client, html: {role: 'form', class: "pure-form pure-form-stacked"} do |f| %>
		
		<fieldset>

			<%= f.label :first_name, "First name *" %>
			<%= f.text_field :first_name, :autofocus => true,
				placeholder: "Enter first name" %>

			<%= f.label :last_name, "Last name *" %>
			<%= f.text_field :last_name, 
				placeholder: "Enter last name" %>

			<%= f.label :phone, "Phone *" %>
			<%= f.text_field :phone, 
				value: "+1" %>

			<%= f.label :contact_id, "MEDA Contact ID" %>
			<%= f.text_field :contact_id, 
				placeholder: "Enter MEDA Contact ID" %>

			<%= f.label :email %>
			<%= f.email_field :email, 
				placeholder: "Enter email" %>

			<%= f.label :salesforce %>
			<%= f.text_field :salesforce_id, 
				placeholder: "Enter Salesforce ID" %>

			<div class='actions'>
				<%= f.submit "Save", class: 'pure-button pure-button-primary' %>
				<%= link_to "Cancel", :back, class: 'pure-button' %>
			</div>
		</fieldset>
	<% end %>
</div>

app/views/clients/edit.html.erb
<div class="pure-g">
  	<div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
  	</div>

	<div class="pure-u-1 pure-u-md-2-3 pure-u-lg-2-3">
    	<div class="main padding">
    	<h2> Edit Client </h2>
			<%= render "form"%>
		</div>
	</div>
</div>

app/views/clients/index.html.erb
<div class="pure-g">
  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
    <div class="sidebar">
      <%= render current_user %>
    </div>
  </div>

  <div class="pure-u-1 pure-u-md-2-3 pure-u-lg-2-3">
      <div class="main padding">
        <%= link_to "Create New Client", new_client_path, class: 'pure-button pure-button-primary' %>
        <%= link_to "Create Group Text", group_new_path, class: 'pure-button button-green' %>

      <div ng-controller="clientsController">

        <h4> Search existing clients </h4>

        <form class="pure-form">
          <input type="text" placeholder="Search by any field..." ng-model="query" autofocus class="pure-input">
        </form>

        <h4> Showing {{filtered.length}} clients</h4>

        <table class="pure-table pure-table-horizontal">
          <thead>
            <tr>
              <td>Name</td>
              <td>Email</td>
              <td>Phone</td>
              <td>MEDA Contact ID</td>
              <td>Salesforce ID</td>
            </tr>
          </thead>
          <tbody>
            <tr ng-repeat="client in filtered = (clients | filter:query:strict)">
              <td><a href="clients/{{ client.id }}">{{client.last_name}}</a></td>
              <td>{{client.email}}</td>
              <td>{{client.phone}}</td>
              <td>{{client.contact_id}}</td>
              <td>{{client.salesforce_id}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<div class="pure-g">
  	<div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
  	</div>

	<div class="pure-u-1 pure-u-md-2-3 pure-u-lg-2-3">
    	<div class="main padding">
    		<h2>New Client</h2>
			<%= render "form"%>
		</div>
	</div>
</div>

app/views/clients/show.html.erb
 <div class="pure-g">
  	<div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
		<%= render partial: "client_sidebar", object: @client %>

		<div class="sidebar">
			<%= link_to "Create New Plan", new_client_action_plan_path(@client),
				class: 'pure-button pure-button-primary block' %>

	    <%= link_to "Send Welcome Text", welcome_clients_path(:client => @client.id), method: :post, class: 'pure-button button-green block', data: { confirm: 'Are you sure you want to send a welcome text?' } %>

	    <%= link_to "Delete Client", @client, method: :delete, class: 'pure-button button-yellow block', data: { confirm: 'Are you sure you want to delete this client?' } %>
    </div>

	</div>

	<div class="pure-u-1 pure-u-md-2-3 pure-u-lg-2-3">
	    <div class="main padding">
				<h3> Action Plans </h3>
				<hr/>
				<%= render @client.action_plans %> 
					<div class="space"></div>
				<h3> Outgoing Text Message Feed (From You) </h3>
				<hr/>
				<%= render @outgoing_texts.sort_by(&:scheduled_date) %>
					<div class="space"></div>
				<h3> Incoming Text Message Feed (From Client) </h3>
				<hr/>
				<%= render @incoming_texts.sort_by(&:scheduled_date) %>
		</div>
	</div>
</div>