config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :path => '',
    :path_names => {:sign_in => 'login', :sign_out => 'logout'},
    :controllers => { registrations: 'registrations' }

  resources :clients do
    resources :action_plans, shallow: true, except: [:index]
  end

  resources :action_plans, shallow: true, only: [] do
    resources :goals, shallow: true, except: [:index]
  end

  resources :goals, shallow: true, only: [] do
    resources :steps, shallow: true, except: [:index, :destroy]
  end

  resources :steps, shallow: true, only: [] do
    resources :text_messages, shallow: true, except: [:index]
  end

  get "text_messages/receive"
  match '/receivetext' => 'text_messages#receive', :via => :post

  resources :clients do
    collection do
      post :welcome
    end
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'group_new' => 'text_messages#group_new'
  post 'group_create' => 'text_messages#group_create'

  root to: 'welcome#index'

end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :goal
  has_many :text_messages

  validates :description, presence: true
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @goal = Goal.find(params[:goal_id])
    @step = @goal.steps.build
    @action_plan = ActionPlan.find(@goal.action_plan_id)
    @client = Client.find(@action_plan[:client_id]) #awkward, but works.
  end

  def create
    @goal = Goal.find(params[:goal_id])
    @action_plan = ActionPlan.find(@goal.action_plan_id)
    @step = @goal.steps.build(step_params)

    if @step.save
      flash[:notice] = "Success!  Step was saved."
      redirect_to @action_plan
    else
      flash[:error] = "There was an error saving the step. Please try again."
      render :new
    end
  end

  def edit
    @step = Step.find(params[:id])
  end

  def update
    @step = Step.find(params[:id])
    @goal = Goal.find(@step.goal_id)
    @action_plan = ActionPlan.find(@goal.action_plan_id)
    @client = Client.find(@action_plan[:client_id])

    if @step.update_attributes(step_params)
      flash[:notice] = "Success!  Step was updated."
      redirect_to @action_plan
    else
      flash[:error] = "There was an error saving the step. Please try again."
      render :edit
    end
  end


  private
  
  def step_params
    params.require(:step).permit(:description, :due_by, :complete)
  end
end

app/views/steps/_form.html.erb
<%= form_for([@goal, @step], html: { class: "pure-form pure-form-stacked" }) do |f| %>
  <div class="form-group">
    <%= f.label "Step description" %>
    <%= f.text_field :description, class: 'pure-input', placeholder: "Enter step description" %>
  </div>

  <div class="form-group">
    <%= f.label "Scheduled Date" %>
    <%= f.date_field :due_by, class: 'pure-input', placeholder: "Enter step due date" %>
  </div>

  <div class="form-group">
    <%= f.label :complete %>
    <%= f.check_box :complete %>
  </div>

  <div>
    <%= f.submit "Save step", class: 'pure-button pure-button-primary' %>
    <%= link_to "Cancel", :back, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/steps/_step.html.erb
<h5>
	<% if current_page?(action_plan_path) %>
		Step <%= format_counter(step_counter) %>: <%= step.description %>

	<%= step.due_by %>
  <% if step.complete == true %>     
  	<span class="icon-award"></span>
  <% else %>
  <span class="icon-flag-checkered"></span>
  <% end %>
		<%= link_to edit_step_path(step) do %>
			<span class="icon-pencil-1"></span>
		<% end %>
	<% end %>
</h5>

<h6>
	<% if current_page?(action_plan_path) %>
		Add messages
		<%= link_to new_step_text_message_path(step) do %>
		<span class="icon-plus-circled"></span>
		<% end %>
	<% end %>
</h6>

<%= render step.text_messages %>

app/views/steps/edit.html.erb
<div class="pure-g">
  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
		<%= render partial: "clients/client_sidebar", object: @client %>
 	</div>

	<div class="pure-u-1 pure-u-md-2-3 pure-u-lg-2-3">
	  <div class="main padding">
		<h3> Edit Step </h3> 
		<%= render 'form' %>
		</div>
	</div>
</div>

app/views/steps/new.html.erb
<div class="pure-g">
  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
		<%= render partial: "clients/client_sidebar", object: @client %>
 	</div>

	<div class="pure-u-1 pure-u-md-2-3 pure-u-lg-2-3">
	  <div class="main padding">
			<%= render 'action_plans/navbar' %>
			<h3>
				Action plan: <%= @action_plan.description %>
			</h3>
			<h4>
				Goal:<%= @goal.description %>
			</h4>
			<%= render 'form' %>
		</div>
	</div>
</div>