config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :path => '',
    :path_names => {:sign_in => 'login', :sign_out => 'logout'},
    :controllers => { registrations: 'registrations' }

  resources :clients do
    resources :action_plans, shallow: true, except: [:index]
  end

  resources :action_plans, shallow: true, only: [] do
    resources :goals, shallow: true, except: [:index]
  end

  resources :goals, shallow: true, only: [] do
    resources :steps, shallow: true, except: [:index, :destroy]
  end

  resources :steps, shallow: true, only: [] do
    resources :text_messages, shallow: true, except: [:index]
  end

  get "text_messages/receive"
  match '/receivetext' => 'text_messages#receive', :via => :post

  resources :clients do
    collection do
      post :welcome
    end
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'group_new' => 'text_messages#group_new'
  post 'group_create' => 'text_messages#group_create'

  root to: 'welcome#index'

end

app/models/action_plan.rb
class ActionPlan < ActiveRecord::Base
  belongs_to :client
  has_many :goals, dependent: :destroy

  validates :description, presence: true
end

app/controllers/action_plans_controller.rb
class ActionPlansController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @client = current_user.clients.find(params[:client_id])
    @action_plan = @client.action_plans.build
  end
  
  def create
    @client = current_user.clients.find(params[:client_id])
    @action_plan = @client.action_plans.build(action_plan_params)
    if @action_plan.save
      flash[:notice] = "Success!  Plan was saved."
      redirect_to @action_plan
    else
      flash[:error] = "There was an error saving the plan. Please try again."
      render :new
    end
  end

  def show
    @action_plan = ActionPlan.find(params[:id])
    @goals = @action_plan.goals.all
    @client = Client.find(@action_plan[:client_id]) 
  end
  
  def edit
    @action_plan = ActionPlan.find(params[:id])
  end
  
  def update
    @action_plan = ActionPlan.find(params[:id])
    # @client = Client.find(@action_plan[:client_id])

    if @action_plan.update_attributes(action_plan_params)
      flash[:notice] = "Success!  Plan was updated."
      redirect_to @action_plan
    else
      flash[:error] = "There was an error saving the plan. Please try again."
      render :edit
    end
  end


  private
  
  def action_plan_params
    params.require(:action_plan).permit(:description)
  end
end

app/views/action_plans/_action_plan.html.erb
<%= div_for action_plan do %>
<h3>
	<%= "#{action_plan.description}" %>
	<%= link_to action_plan_path(action_plan) do %>
			<span class="icon-pencil-1"></span>
	<% end %>
</h3>
<% end %>

app/views/action_plans/_form.html.erb
<div class="col-md-8">
<%= form_for([@client, @action_plan]) do |f| %>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_field :description, class: 'form-control',
			placeholder: "Enter description" %>
	</div>
	<div class="form-group">
		<%= link_to "Cancel", :back, class: 'btn btn-default' %>
		<%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/action_plans/_navbar.html.erb
<div>
	<h3 class="margin">
	Add Goals
	<span class="icon-right-open-big"></span>
	Add Steps
	<span class="icon-right-open-big"></span>
	Send Messages
	</h3>
</div>

app/views/action_plans/edit.html.erb
<h3>Edit Action Plan</h3>

<%= render 'form' %>

app/views/action_plans/new.html.erb
<div class="pure-g">
  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
		<%= render partial: "clients/client_sidebar", object: @client %>
  </div>

  <div class="pure-u-1 pure-u-md-2-3 pure-u-lg-2-3">
      	<div class="main padding">

		<%= render 'navbar' %>
	
			<div>
				<%= form_for([@client, @action_plan], html: { class: "pure-form pure-form-stacked" } ) do |f| %>
					<div class= "inline">
							<%= f.label :title_of_action_plan %>
							<%= f.text_field :description, class: 'pure-input',
								placeholder: "Enter title of action plan (e.g., 12/31/14 Meeting with Maria)" %>
						<%= f.submit "Create action plan", class: 'pure-button pure-button-primary' %>
				  </div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/action_plans/show.html.erb
<div class="pure-g">
  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
		<%= render partial: "clients/client_sidebar", object: @client %>
	</div>

	<div class="pure-u-1 pure-u-md-1-3 pure-u-lg-2-3">
    <div class="main padding">
			<!--<%= render 'navbar' %>-->
			<h3>
				Action plan: <%= @action_plan.description %>
				<%= link_to edit_action_plan_path(@action_plan) do %>
						<span class="icon-pencil-1"></span>
				<% end %>
			</h3>

			<h6>
				<% if current_page?(action_plan_path) %>
					Add goals
					<%= link_to new_action_plan_goal_path(@action_plan) do %>	
						<span class="icon-plus-circled"></span>
					<% end %>
				<% end %>
			</h6>

		<%= render @goals %>

		</div>
	</div>
</div>