config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :path => '',
    :path_names => {:sign_in => 'login', :sign_out => 'logout'},
    :controllers => { registrations: 'registrations' }

  resources :clients do
    resources :action_plans, shallow: true, except: [:index]
  end

  resources :action_plans, shallow: true, only: [] do
    resources :goals, shallow: true, except: [:index]
  end

  resources :goals, shallow: true, only: [] do
    resources :steps, shallow: true, except: [:index, :destroy]
  end

  resources :steps, shallow: true, only: [] do
    resources :text_messages, shallow: true, except: [:index]
  end

  get "text_messages/receive"
  match '/receivetext' => 'text_messages#receive', :via => :post

  resources :clients do
    collection do
      post :welcome
    end
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'group_new' => 'text_messages#group_new'
  post 'group_create' => 'text_messages#group_create'

  root to: 'welcome#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :action_plan
  has_many :steps, dependent: :destroy

  validates :description, presence: true
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @action_plan = ActionPlan.find(params[:action_plan_id])
    @goal = @action_plan.goals.build
    @goals = @action_plan.goals.all
    @client = Client.find(@action_plan[:client_id]) #awkward, but works.
  end

  def create
    @action_plan = ActionPlan.find(params[:action_plan_id])
    @goal = @action_plan.goals.build(goal_params)
    if @goal.save
      flash[:notice] = "Success!  Goal was saved."
      redirect_to @action_plan
    else
      flash[:error] = "There was an error saving the goal. Please try again."
      render :new
    end
  end

  def show
    @action_plan = ActionPlan.find(params[:action_plan_id])
    @goals = @action_plan.goals.all
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    @action_plan = ActionPlan.find(@goal.action_plan_id)
    # @client = Client.find(@action_plan[:client_id])

    if @goal.update_attributes(goal_params)
      flash[:notice] = "Success!  Goal was updated."
      redirect_to @action_plan
    else  
      flash[:error] = "There was an error saving the goal. Please try again."
      render :edit
    end
  end


  private
  
  def goal_params
    params.require(:goal).permit(:description)
  end
end

app/helpers/goal_helper.rb
module GoalHelper
  def format_counter(counter)
    counter + 1
  end
end

app/views/goals/_form.html.erb
<%= form_for([@action_plan, @goal], html: { class: "pure-form" }) do |f| %>
	<div>
		<%= f.text_field :description, class: 'pure-input', placeholder: "Enter goal description" %>
		<%= f.submit "Save goal", class: 'pure-button pure-button-primary' %>
		<%= link_to "Cancel", :back %>
	</div>
<% end %>

app/views/goals/_goal.html.erb
	<h4>
		Goal <%= format_counter(goal_counter) %>: <%= goal.description %>
		<% if current_page?(action_plan_path) %>
			<%= link_to edit_goal_path(goal) do %>
				<span class="icon-pencil-1"></span>
			<% end %>
		<% end %>
	</h4>

	<h6>
		<% if current_page?(action_plan_path) %>
			Add steps to Goal 		
			<%= link_to new_goal_step_path(goal) do %>
			<span class="icon-plus-circled"></span>
			<% end %>
		<% end %>
	</h6>
	<%= render goal.steps %>
<% if goal.steps.present? %>
	<% if current_page?(client_path) %>
		<div>
			Due Date Status Messages (Sent / Total)
		</div>
	<% end %>
<% end %>

app/views/goals/edit.html.erb
<h3>Edit Goal</h3>

<%= render 'form' %>

app/views/goals/new.html.erb
 <div class="pure-g">
  	<div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
		<%= render partial: "clients/client_sidebar", object: @client %>
 	</div>
	<div class="pure-u-1 pure-u-md-2-3 pure-u-lg-2-3">
	  <div class="main padding">
		<%= render 'action_plans/navbar' %>
		<h3>
				Action plan: <%= @action_plan.description %>
				<%= link_to edit_action_plan_path(@action_plan) do %>
						<span class="icon-pencil-1"></span>
				<% end %>
			</h3>

			<br>

			<%= render 'form' %>

		</div>
	</div>
</div>